export const SEED_APPS = [
  { name: "GPay", emoji: "💳" },
  { name: "WhatsApp", emoji: "💬" },
  { name: "Airtel", emoji: "📶" },
  { name: "Amazon", emoji: "📦" },
  { name: "YouTube", emoji: "▶️" },
  { name: "Zepto", emoji: "🛒" },
  { name: "Instagram", emoji: "📸" },
  { name: "Gmail", emoji: "📧" },
  { name: "Slack", emoji: "💬" },
  { name: "LinkedIn", emoji: "💼" },
  { name: "Twitter", emoji: "🐦" },
  { name: "Spotify", emoji: "🎵" },
  { name: "Netflix", emoji: "🎬" },
  { name: "Uber", emoji: "🚗" },
  { name: "Zomato", emoji: "🍕" },
  { name: "Snapchat", emoji: "👻" },
  { name: "Discord", emoji: "👾" },
  { name: "Telegram", emoji: "✈️" },
  { name: "Facebook", emoji: "👥" },
  { name: "TikTok", emoji: "🎵" },
];
